// Turns a blueprint into a real, runnable app: Claude generates a complete
// self-contained HTML app (screens wired to mock data, agent behaviour
// simulated deterministically), we write it to disk and serve it at /app/<slug>.
const fs = require('fs');
const path = require('path');
const { authenticate, requireAnthropic, claudeJSON } = require('./_lib');

const APPS_DIR = path.join(__dirname, '..', 'apps');

module.exports = async (req, res) => {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Use POST' });
  const auth = await authenticate(req, res);
  if (!auth) return;
  if (!requireAnthropic(res)) return;

  const b = req.body || {};
  const name = String(b.name || 'app').slice(0, 60);
  const env = b.env === 'production' ? 'production' : 'staging';
  const blueprint = b.blueprint && Array.isArray(b.blueprint) ? b.blueprint : null;
  if (!blueprint) return res.status(400).json({ error: 'Blueprint missing' });

  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40) || 'app';
  const stamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);

  const log = [
    `Generating app from blueprint (${blueprint.reduce((a, l) => a + l.items.length, 0)} parts)`,
    'Asking the model for a complete implementation'
  ];

  const prompt = `You are a senior developer. From the app blueprint below, generate a COMPLETE, runnable, self-contained prototype web app as a single HTML file. Requirements:
- One HTML file with inline CSS and JS, no external dependencies or CDNs.
- Implement every screen in the blueprint as a real view (sidebar or tab navigation), populated with realistic mock data (10-15 rows) shown in a table/cards.
- Simulate the agents' behaviour deterministically in JS: buttons like "Run agent" / "Process next" apply the agents' stated rules to the mock data and show the result plus a visible trace of steps taken.
- Honour permissions: actions the blueprint marks as not allowed must be disabled with a note.
- Clean, modern, minimal design. Keep the file under 400 lines.

Blueprint (JSON):
${JSON.stringify(blueprint).slice(0, 6000)}

Reply with JSON only: {"index.html": "<the full file>"}`;

  const out = await claudeJSON(prompt, { maxTokens: 8000, timeoutMs: 90000 });
  if (out.error) {
    log.push(out.error);
    return res.status(502).json({ error: out.error, log });
  }
  const html = out.json && typeof out.json['index.html'] === 'string' ? out.json['index.html'] : null;
  if (!html || html.length < 500) {
    return res.status(502).json({ error: 'The model did not return a usable app', log });
  }

  const dir = path.join(APPS_DIR, `${slug}-${env}`);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'index.html'), html);
  fs.writeFileSync(path.join(dir, 'README.md'),
    `# ${name}\n\nGenerated by Architect from a blueprint on ${stamp}.\nOpen index.html or visit /app/${slug}-${env}/\n`);

  log.push(`Wrote ${(html.length / 1024).toFixed(1)} KB app`, `Live at /app/${slug}-${env}/`);
  const url = `/app/${slug}-${env}/`;

  // Record the deployment when signed in and tied to a project
  const projectId = String(b.project_id || '');
  if (auth.user && projectId) {
    fetch(`${process.env.SUPABASE_URL}/rest/v1/deployments`, {
      method: 'POST',
      headers: {
        apikey: process.env.SUPABASE_ANON_KEY,
        Authorization: `Bearer ${auth.token}`,
        'Content-Type': 'application/json',
        Prefer: 'return=minimal'
      },
      body: JSON.stringify({ project_id: projectId, env, url, detail: `${(html.length / 1024).toFixed(1)} KB generated app` })
    }).catch(() => {});
  }

  res.status(200).json({ url, log });
};
